### ISSUE TITLE
配置http2

### ISSUE THREAD

**Issue by yanhuiyi** [haoel/haoel.github.io#19]
@haoel

请问在启动gost容器的之前，是否需要配置我的服务器(web服务器？我这里是在debian9上安装的apache2）支持http2协议？这里的USER:PASS两个变量应该是http2这个服务器上设置的？

"http2://${USER}:${PASS}@${BIND_IP}:${PORT}?cert=${CERT}&key=${KEY}&probe_resist=code:404"

运行docker gost后退出了 服务好像没有启动成功。

**Comment by VincentSit** [comment]
1. gost has no dependencies, you don't need to install any web server.
2. The tutorial is very detailed and novice-friendly, you are not required to install any web server. Please follow the tutorial step by step if you are a newbie.
3. The reason for the startup failure I guess is because your server's apache listens on port 443 and conflicts with the port 443 that gost listens on. Please check the container's log via `docker logs gost` to troubleshoot the issue.

**Comment by yanhuiyi** [comment]
Thanks your reply @vincentSit. I've made it work today and are able to access website. You're right it's the port 443 used by apache that caused the gost service failing to start. My final setup toolset is, GCP + Gost + SS.

**Comment by FlyFlame** [comment]
也就是说需要在VPS上也安装shadowsocks server吗？教程里没讲清楚gost和shadowsocks分别在Linux本地和VPS服务器上怎么配置，还想请教您一下？
